[package]
name = "gpt-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.2.2"
dotenv = "0.15.0"
reqwest = "0.11.16"
tokio = {version = "1.27.0", features = ["full"]}
